# Generated by Django 4.2.7 on 2026-01-02 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("voice_reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicereport",
            name="edited_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last edited the SQL",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="edited_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="voicereport",
            name="sql_edited",
            field=models.BooleanField(
                default=False, help_text="Has SQL been manually edited"
            ),
        ),
        migrations.AlterField(
            model_name="voicereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Audio Uploaded"),
                    ("transcribing", "Transcribing"),
                    ("transcribed", "Transcribed"),
                    ("generating_sql", "Generating SQL"),
                    ("sql_generated", "SQL Generated"),
                    ("pending_execution", "Pending Execution"),
                    ("executing", "Executing Query"),
                    ("executed", "Executed"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
