# Generated by Django 4.2.7 on 2026-04-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice_reports", "0004_add_preprocessing_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicereport",
            name="pipeline_trace",
            field=models.JSONField(
                blank=True,
                help_text="Full analyst-grade execution trace for the AI pipeline",
                null=True,
            ),
        ),
    ]
