# Generated by Django 4.2.7 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice_reports", "0005_add_pipeline_trace"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicereport",
            name="ai_trace",
            field=models.JSONField(
                blank=True,
                help_text="Normalized AI transparency trace for analyst explainability UI",
                null=True,
            ),
        ),
    ]
