# Generated by Django 5.2.8 on 2026-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_add_workspace_company_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='owner_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='is_user_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='is_user_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='user_role',
            field=models.CharField(choices=[('manager', 'Manager'), ('analyst', 'Analyst'), ('executive', 'Executive')], default='analyst', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='owner',
            field=models.PositiveBigIntegerField(db_column='owner_id', db_index=True),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('analyst', 'Analyst'), ('executive', 'Executive')], default='analyst', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='user',
            field=models.PositiveBigIntegerField(blank=True, db_column='user_id', db_index=True, null=True),
        ),
        migrations.RunSQL(
            sql="""
                UPDATE workspaces AS w
                SET
                    owner_email = COALESCE(u.email, w.owner_email, ''),
                    owner_name = COALESCE(u.name, w.owner_name, '')
                FROM users AS u
                WHERE w.owner_id = u.id
                  AND (
                      COALESCE(w.owner_email, '') = ''
                      OR COALESCE(w.owner_name, '') = ''
                  );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                UPDATE workspace_members AS wm
                SET
                    user_email = COALESCE(u.email, wm.user_email, wm.invited_email, ''),
                    user_name = COALESCE(u.name, wm.user_name, ''),
                    user_role = CASE
                        WHEN COALESCE(u.role, '') IN ('manager', 'analyst', 'executive')
                            THEN u.role
                        ELSE COALESCE(NULLIF(wm.user_role, ''), wm.role, 'analyst')
                    END,
                    is_user_active = COALESCE(u.is_active, wm.is_user_active, TRUE),
                    is_user_verified = COALESCE(u.is_verified, wm.is_user_verified, FALSE)
                FROM users AS u
                WHERE wm.user_id IS NOT NULL
                  AND wm.user_id = u.id
                  AND (
                      COALESCE(wm.user_email, '') = ''
                      OR COALESCE(wm.user_name, '') = ''
                      OR COALESCE(wm.user_role, '') = ''
                  );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
