# Generated by Django 5.2 on 2025-11-27 15:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workspacemember",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="invited_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="invited_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="role",
            field=models.CharField(
                choices=[("analyst", "Analyst"), ("executive", "Executive")],
                default="analyst",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_registration", "Pending Registration"),
                    ("pending_acceptance", "Pending Acceptance"),
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                ],
                default="active",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="joined_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(
                fields=["workspace", "user"], name="workspace_m_workspa_7679d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workspacemember",
            index=models.Index(
                fields=["workspace", "invited_email"],
                name="workspace_m_workspa_ddd742_idx",
            ),
        ),
    ]
