# Generated by Django 4.2.7 on 2026-01-01 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                (
                    "file_path",
                    models.CharField(
                        help_text="Path to file in ETL system", max_length=500
                    ),
                ),
                (
                    "row_count",
                    models.IntegerField(
                        default=0, help_text="Number of rows in the dataset"
                    ),
                ),
                (
                    "column_count",
                    models.IntegerField(
                        default=0, help_text="Number of columns in the dataset"
                    ),
                ),
                (
                    "columns_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Column names and types as JSON",
                    ),
                ),
                (
                    "clickhouse_table_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the table in ClickHouse",
                        max_length=255,
                    ),
                ),
                (
                    "clickhouse_database",
                    models.CharField(
                        default="default",
                        help_text="ClickHouse database name",
                        max_length=255,
                    ),
                ),
                (
                    "upload_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "etl_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "etl_message",
                    models.TextField(
                        blank=True, help_text="ETL processing message/error"
                    ),
                ),
                (
                    "manager",
                    models.OneToOneField(
                        limit_choices_to={"role": "manager"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="database",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Database",
                "verbose_name_plural": "Databases",
                "db_table": "manager_databases",
                "ordering": ["-upload_date"],
            },
        ),
    ]
