# Generated by Django 5.2.8 on 2026-05-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='manager_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='database',
            name='manager_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='database',
            name='workspace_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, help_text='Workspace identifier from workspace-service.', null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='manager',
            field=models.PositiveBigIntegerField(db_column='manager_id', db_index=True, help_text='Manager user identifier from auth-service.', unique=True),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE manager_databases AS md "
                "SET manager_email = COALESCE(u.email, ''), manager_name = COALESCE(u.name, '') "
                "FROM users AS u "
                "WHERE md.manager_id = u.id;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE manager_databases AS md "
                "SET workspace_id = w.id "
                "FROM workspaces AS w "
                "WHERE md.manager_id = w.owner_id AND md.workspace_id IS NULL;"
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
