# Generated by Django 4.2.7 on 2026-01-02 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workspace", "0004_remove_old_invitation_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("metabase_dashboard_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_pages",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Page",
                "verbose_name_plural": "Dashboard Pages",
                "db_table": "dashboard_pages",
                "ordering": ["workspace", "order"],
            },
        ),
        migrations.CreateModel(
            name="VoiceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        help_text="Audio file path: /media/workspaces/{workspace_id}/audio/",
                        upload_to="workspaces/%Y/%m/%d/",
                    ),
                ),
                (
                    "audio_duration",
                    models.FloatField(
                        blank=True, help_text="Duration in seconds", null=True
                    ),
                ),
                (
                    "transcription",
                    models.TextField(blank=True, help_text="Whisper STT output"),
                ),
                (
                    "transcription_language",
                    models.CharField(blank=True, default="en", max_length=10),
                ),
                (
                    "intent_json",
                    models.JSONField(
                        blank=True, help_text="Extracted intent from text", null=True
                    ),
                ),
                (
                    "generated_sql",
                    models.TextField(blank=True, help_text="Generated SQL query"),
                ),
                (
                    "final_sql",
                    models.TextField(
                        blank=True, help_text="Final SQL after validation/edits"
                    ),
                ),
                ("sql_validated", models.BooleanField(default=False)),
                (
                    "query_result",
                    models.JSONField(
                        blank=True, help_text="Query execution result", null=True
                    ),
                ),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("row_count", models.IntegerField(blank=True, null=True)),
                (
                    "chart_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("number", "Number/KPI"),
                            ("table", "Table"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "chart_config",
                    models.JSONField(
                        blank=True, help_text="Chart configuration", null=True
                    ),
                ),
                ("metabase_question_id", models.IntegerField(blank=True, null=True)),
                ("metabase_dashboard_id", models.IntegerField(blank=True, null=True)),
                (
                    "embed_url",
                    models.TextField(blank=True, help_text="JWT-signed embed URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Audio Uploaded"),
                            ("transcribing", "Transcribing"),
                            ("transcribed", "Transcribed"),
                            ("generating_sql", "Generating SQL"),
                            ("sql_generated", "SQL Generated"),
                            ("executing", "Executing Query"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated or user-provided",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voice_reports",
                        to="workspace.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voice Report",
                "verbose_name_plural": "Voice Reports",
                "db_table": "voice_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SQLEditHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_sql", models.TextField()),
                ("new_sql", models.TextField()),
                ("validation_passed", models.BooleanField(default=False)),
                ("validation_errors", models.JSONField(blank=True, null=True)),
                ("edited_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "edited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sql_history",
                        to="voice_reports.voicereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "SQL Edit History",
                "verbose_name_plural": "SQL Edit Histories",
                "db_table": "sql_edit_history",
                "ordering": ["-edited_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportPageAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("added_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_assignments",
                        to="voice_reports.dashboardpage",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_assignments",
                        to="voice_reports.voicereport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Page Assignment",
                "verbose_name_plural": "Report Page Assignments",
                "db_table": "report_page_assignments",
                "ordering": ["page", "order"],
            },
        ),
        migrations.AddIndex(
            model_name="voicereport",
            index=models.Index(
                fields=["workspace", "created_by"],
                name="voice_repor_workspa_bcddb4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="voicereport",
            index=models.Index(
                fields=["workspace", "status"], name="voice_repor_workspa_033512_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="voicereport",
            index=models.Index(
                fields=["created_at"], name="voice_repor_created_d56b7e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reportpageassignment",
            unique_together={("report", "page")},
        ),
        migrations.AlterUniqueTogether(
            name="dashboardpage",
            unique_together={("workspace", "name")},
        ),
    ]
