# Generated by Django 4.2.7 on 2026-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice_reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicereport",
            name="edited_by",
            field=models.CharField(
                blank=True,
                db_column="edited_by_id",
                help_text="User who last edited the SQL",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="voicereport",
            name="sql_edited",
            field=models.BooleanField(
                default=False, help_text="Has SQL been manually edited"
            ),
        ),
        migrations.AlterField(
            model_name="voicereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Audio Uploaded"),
                    ("transcribing", "Transcribing"),
                    ("transcribed", "Transcribed"),
                    ("generating_sql", "Generating SQL"),
                    ("sql_generated", "SQL Generated"),
                    ("pending_execution", "Pending Execution"),
                    ("executing", "Executing Query"),
                    ("executed", "Executed"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
    ]
