# Generated by Django 4.2.7 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice_reports", "0003_update_chart_and_status_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicereport",
            name="preprocessing_high",
            field=models.JSONField(
                blank=True,
                help_text="High-level schema-aware preprocessing metadata",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="voicereport",
            name="preprocessing_low",
            field=models.JSONField(
                blank=True,
                help_text="Low-level text preprocessing metadata",
                null=True,
            ),
        ),
    ]
