# Generated by Django 4.2.7 on 2026-03-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voice_reports", "0002_add_sql_editing_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voicereport",
            name="chart_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("line", "Line Chart"),
                    ("bar", "Bar Chart"),
                    ("pie", "Pie Chart"),
                    ("kpi", "KPI"),
                    ("table", "Table"),
                    ("number", "Legacy Number/KPI"),
                    ("scalar", "Legacy Scalar"),
                    ("grouped_bar", "Legacy Grouped Bar"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voicereport",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Audio Uploaded"),
                    ("transcribing", "Transcribing"),
                    ("transcribed", "Transcribed"),
                    ("generating_sql", "Generating SQL"),
                    ("sql_generated", "SQL Generated"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("executed", "Executed"),
                    ("visualization_created", "Visualization Created"),
                    ("failed", "Failed"),
                    ("pending_execution", "Legacy Pending Execution"),
                    ("executing", "Legacy Executing Query"),
                    ("completed", "Legacy Completed"),
                ],
                default="uploaded",
                max_length=32,
            ),
        ),
    ]
