# Generated by Django 5.2.8 on 2026-05-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_fields_and_password_reset_codes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='password_re_email_49e213_idx',
            old_name='password_re_email_994d9f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='password_re_user_id_c7cc25_idx',
            old_name='password_re_user_id_51447f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='password_re_expires_8cf690_idx',
            old_name='password_re_expires_b5be6c_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('analyst', 'Analyst'), ('executive', 'Executive')], max_length=20),
        ),
    ]
