apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-service
  namespace: etl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata-service
  template:
    metadata:
      labels:
        app: metadata-service
    spec:
      containers:
        - name: metadata-service
          image: etl-final/metadata-service:latest
          ports:
            - containerPort: 8006
          envFrom:
            - configMapRef:
                name: etl-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8006
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8006
            initialDelaySeconds: 10
            periodSeconds: 20
