apiVersion: apps/v1
kind: Deployment
metadata:
  name: transformer-service
  namespace: etl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transformer-service
  template:
    metadata:
      labels:
        app: transformer-service
    spec:
      containers:
        - name: transformer-service
          image: etl-final/transformer-service:latest
          ports:
            - containerPort: 8004
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: etl-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 20
