"""
Django settings for connector project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from shared.utils.logging_utils import configure_logging
from shared.utils.tracing import configure_tracing

configure_logging()
configure_tracing("connector-service")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eudpuhmm^o!=%tqkoi%b+gt9)!1zvjkhf*%-^81_7q1gz_^=5^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'etl_engine',
    'rest_framework',
]
MEDIA_URL = '/uploads/'
MEDIA_ROOT = BASE_DIR / '../uploaded_files'
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800

# File validation settings
import os
MAX_FILE_SIZE = int(os.environ.get('MAX_FILE_SIZE', 1073741824))  # Default: 1GB (1024*1024*1024)

# Virus scanning settings
VIRUS_SCAN_ENABLED = os.environ.get('VIRUS_SCAN_ENABLED', 'True').lower() in ('true', '1', 'yes')
VIRUS_SCAN_BACKEND = os.environ.get('VIRUS_SCAN_BACKEND', 'clamav')  # 'clamav' or 'mock'
CLAMAV_HOST = os.environ.get('CLAMAV_HOST', 'clamav')
CLAMAV_PORT = int(os.environ.get('CLAMAV_PORT', 3310))
CLAMAV_TIMEOUT = int(os.environ.get('CLAMAV_TIMEOUT', 30))

# Input validation settings
MAX_REQUEST_SIZE = int(os.environ.get('MAX_REQUEST_SIZE', 10485760))  # Default: 10MB

# Rate limiting settings
RATE_LIMIT_ENABLED = os.environ.get('RATE_LIMIT_ENABLED', 'True').lower() in ('true', '1', 'yes')
RATE_LIMIT_REQUESTS = int(os.environ.get('RATE_LIMIT_REQUESTS', 100))  # requests per window (per IP)
RATE_LIMIT_WINDOW = int(os.environ.get('RATE_LIMIT_WINDOW', 60))  # seconds
RATE_LIMIT_PER_USER_REQUESTS = int(os.environ.get('RATE_LIMIT_PER_USER_REQUESTS', 200))  # requests per window (per authenticated user)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'shared.utils.django_middleware.CorrelationIdMiddleware',
    'shared.utils.django_middleware.MetricsMiddleware',
    # Custom middleware for input validation and security
    'etl_engine.middleware.RequestValidationMiddleware',
    'etl_engine.middleware.RateLimitMiddleware',
    'etl_engine.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'connector.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'connector.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
